# Secrets for Sensitive Configuration
# Stores database credentials (base64 encoded)
#
# IMPORTANT: This is for LOCAL DEVELOPMENT ONLY
# In production, use external secret management (e.g., Vault, AWS Secrets Manager)
#
# To encode values:
# echo -n 'postgres' | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev
  labels:
    app: microservices
    component: secrets
type: Opaque
data:
  # Database username: postgres
  DB_USERNAME: cG9zdGdyZXM=
  # Database password: postgres
  DB_PASSWORD: cG9zdGdyZXM=
